### ISSUE TITLE
POST /register

### ISSUE THREAD

**Issue by kparkov** [bitkompagniet/mugs#2]
## Tasks

- [ ] Store register method
- [ ] API endpoint `POST /register`
- [ ] Send e-mail

## POST body

```javascript
{
	"email": String,
	"fullname": String,
	"password": String,
	"data": {},
}
```

## Response codes

| Code | Meaning                      |
|------------------|------------------------------|
| 200 OK | Registration OK.      |
| 400 BAD REQUEST  | The post body was invalid.    |

## Acceptance criteria

- [ ] At registration, we can post e-mail, fullname, password and data. Everything else is ignored.
- [ ] A registration e-mail is sent with the automatically generated confirmation token.
- [ ] The posted data is returned, but without any tokens.
