### ISSUE TITLE
Send e-mails

### ISSUE THREAD

**Issue by kparkov** [bitkompagniet/mugs#4]
## Tasks

- [x] Given an SMTP connection string and using the [nodemailer](https://www.npmjs.com/package/nodemailer) module, we can send e-mails based on [handlebars](https://www.npmjs.com/package/handlebars).
- [x] All handlebars templates should receive `_id`, `email` and `fullname` of the user in question.
- [x] Default e-mail template for registration with a confirmation token (from user model).
- [x] Default e-mail template for sending a password recovery token (from user model).
- [ ] Wire up sending the correct mail in the corresponding events.

evt:
- [ ] Default e-mail template for notifying when the registration was confirmed.
- [ ] Default e-mail template for confirming that password was changed.

## For testing

This connection string can be used for testing: `smtps://system@bitkompagniet.dk:hattefar@smtp.gmail.com:465`
